import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import {
  Container,Row, Col,
  Button,
  Input,
  Spacer,
  Link,
  Card,
  Grid,
  useTheme, Text
  
} from '@nextui-org/react';
export default function Home() {
  
  const { theme } = useTheme();
  const colors = [
    'primary',
    'secondary',
    'success',
    'warning',
    'error',
    'gradient'
    
  ];
  const MockItem = ({text}) => {
    return (
        <div height={100}>
            <Text h6 size={15} color="white" style={{ margin: 0 }}>
                {text}
            </Text>
        </div>
    );
}



  return (
    <div className={styles.container}>
      <Head>
        <title>NextUI | Create Next App</title>
        <meta
          name="description"
          content="Generated by create next app and using NextUI as a react UI library"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Grid.Container gap={2} justify="center">
        <Grid xs><MockItem text="1 of 3" /></Grid>
        <Grid xs><MockItem text="2 of 3" /></Grid>
        <Grid xs><MockItem text="3 of 3" /></Grid>
      </Grid.Container>
      <Grid.Container gap={2} justify="center">
        <Grid xs><MockItem text="1 of 3" /></Grid>
        <Grid xs={6}><MockItem text="2 of 3" /></Grid>
        <Grid xs><MockItem text="3 of 3" /></Grid>
      </Grid.Container>
      
        <Card css={{ px: '$4' }}>
          <Text
            h1
            size={60}
            css={{
              textGradient: '45deg, $blue500 -20%, $pink500 50%'
            }}
            weight="bold"
          >
            Let's
          </Text>
          <Text
            h1
            size={60}
            css={{
              textGradient: '45deg, $purple500 -20%, $pink500 100%'
            }}
            weight="bold"
          >
            Make the Web
          </Text>
          <Text
            h1
            size={60}
            css={{
              textGradient: '45deg, $yellow500 -20%, $red500 100%'
            }}
            weight="bold"
          >
            Prettier
          </Text>
        </Card>
        <div>
              <p
                style={{
                  color: theme.colors.warning.value,
                  fontSize: theme.fontSizes.tiny.value,
                  padding: `${theme.space[2].value} ${theme.space[4].value}`
                }}
              >
                Using color theme value
              </p>
              <Text
                css={{
                  color: '$gray800',
                  fontSize: '$tiny',
                  padding: '$2 $4'
                }}
              >
                base text
              </Text>
        </div>
        <Grid.Container gap={2}>
        {colors.map((color) => (
              <Grid xs={12} md={4} key={color}>
                <Card color={color}>
                  <Text css={{ fontWeight: '$bold', color: '$white' }} transform="capitalize">
                    herohoro
                  </Text>
                  <Text css={{ fontWeight: '$bold', color: '$white' }} span>herohoro</Text>
                </Card>
              </Grid>
            ))}
        </Grid.Container>

        <Card css={{ mw: "400px" }}>
          <p>A basic card.</p>
        </Card>
        <Card bordered shadow={false} hoverable css={{ mw: "400px" }}>
          <p>A hoverable card.</p>
        </Card>
        <Card clickable bordered css={{ mw: "400px" }}>
          <p>A clickable card.</p>
        </Card>
        <Card clickable bordered css={{ mw: "400px" }} bordered shadow={false} hoverable css={{ mw: "400px" }}>
          <p>A clickable card + hoverable card.</p>
        </Card>
        <Container >
        <Spacer />
        <Image src="/../public/vercel.svg" alt="Vercel Logo" width={200} height={200} />
        <Spacer />
        <Row justify="center" align="center">
      
        <Text h3 color="secondary">
          Welcome to&nbsp;
          <Link
            color="warning"
            href="https://nextjs.org"
            target="_blank"
            rel="noopener noreferrer"
          >
            Next.js
          </Link>
          &nbsp;&&nbsp;
          <Link
            icon
            underline
            href="https://nextui.org"
            target="_blank"
            rel="noopener noreferrer"
          >
            NextUI
          </Link>
        </Text>
        </Row>
        <Spacer />
        <Row justify="center" align="center">
        
        <Input clearable labelPlaceholder="Type something" />
        <Spacer />
        <Button>
          <a
            className={styles.button}
            href="https://github.com/nextui-org/nextui"
            target="_blank"
            rel="noopener noreferrer"
          >
            Show on Github
          </a>
        </Button>
        </Row>
        <Spacer y={3}/>
        
        </Container>
        
    </div>
  )
}